version: '3'
volumes:
  video-streaming-db:
services: 
  streaming:
    build: 
      context: ./streaming
      dockerfile: Dockerfile-dev
    environment: 
      - PORT=80
      - STORAGE_HOST=google-storage
      - STORAGE_PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on: 
      - db
      - google-storage
      - rabbit
    ports:
      - "8080:80"
    volumes:
      - ./streaming:/src
    restart: "no"
  google-storage:
    build: 
      context: ./google-storage
      dockerfile: Dockerfile-dev
    environment:
      - PORT=80
      - GOOGLE_APPLICATION_CREDENTIALS=./gcs.json
      - PROJECT_ID=video-streaming-306005
    ports:
      - "8081:80"
    volumes:
      - ./google-storage:/src
    restart: "no"
  history:
    build: 
      context: ./history
      dockerfile: Dockerfile-dev
    environment:
      - PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
      - RABBIT=amqp://guest:guest@rabbit:5672
    ports:
      - "8082:80"
    volumes:
      - ./history:/src
    depends_on:
      - db
      - rabbit
    restart: "no"
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "8083:27017"
    restart: always
    volumes: 
      - video-streaming-db:/data/db
  rabbit:
    image: rabbitmq:3.8.1-management 
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
