version: '3'
services: 
  streaming:
    build: streaming
    environment: 
      - PORT=8080
    ports:
      - "8080:8080"
    restart: "no"
  google-storage:
    build: google-storage
    environment:
      - PORT=8081
      - GOOGLE_APPLICATION_CREDENTIALS=./gcs.json
      - PROJECT_ID=video-streaming-306005
    ports:
      - "8081:8081"
